Added first week closed on registration.php
CompCamps/WebsiteArchive pull request #51
Opened 2018-06-24 22:58 UTC by trollmad3

I noticed the first week is closed and it will help out people. Let's say they enter all the registration and find out the first week is closed at the end.

2018-06-24 23:50 UTC, BrettMayson requested changes

2018-06-24 23:50 UTC, synixebrett commented on www/index.php
> +      <a class="reddit" href="https://www.reddit.com/r/compcamps/"><i class="fab fa-3x fa-reddit></i></a>
This is unrelated to this pull request and needs to be removed

2018-06-24 23:50 UTC, synixebrett commented on www/register.php
> +  <h3>Secound week: OPEN</h3>
This is not spelled correctly

2018-06-25 00:58 UTC, trollmad3 commented on www/register.php
> +  <h3>Secound week: OPEN</h3>
Isn't it spelt week?

2018-06-25 01:02 UTC, Aholicknight reviewed
Fixed typo.

2018-06-25 01:02 UTC, trollmad3 commented on www/register.php
> +  <h3>Secound week: OPEN</h3>
Typo fixed.

2018-06-26 20:45 UTC, BrettMayson approved these changes

2018-06-26 20:45 UTC, merged